WIP Isomorphic aliases
VKCOM/elephize pull request #16
Opened 2020-08-12 23:20 UTC by ctizen

2020-08-19 07:44 UTC, fix-fix requested changes

2020-08-19 07:44 UTC, fix-fix commented on src/ts2php/types.ts
> +  importRules: {
стоит задокументировать формат настройки importRules и/или добавить пример: конфига, и js- и php-модулей

можно не в этом PR, особенно если формат не устаканился

2020-08-19 07:44 UTC, fix-fix commented on elephizerc.example.json
>    "customGlobals": {
можно удалить, такого конфига вроде больше нет

2020-08-19 07:44 UTC, fix-fix commented on src/ts2php/components/cjsModules/phpParser.ts
> +        return $this->_impl->${name}(${args});
Правильно ли я понял, что у класса-подмены (который `implementationClass`) вызываются именно только методы *инстанса*, а не *статичные* методы?

И если мне например надо использовать какие-то статичные методы из существующих PHP-классов, то надо будет добавить в коде дополнительную обёртку?

2020-08-19 07:44 UTC, fix-fix commented on .gitattributes
> +src/vendor/**/* linguist-generated
придирка: в комментарии коммита написано про ревет коммита 7307f76d7c9870ce2e0ec5ed5c8b9ca83fd312a2, но я такого не нашёл

в любом случае сейчас непонятно, зачем потребовался вендоринг (не видно ни по истории коммитов, ни по README).

можешь добавить пояснение о необходимых патчах или причинах вендоринга в README?

2020-08-19 07:44 UTC, fix-fix commented on package.json
> +    "@mattacosta/php-common": "^1.0.0-beta.4",
придирка: скорее всего можно оставить в завендоренном пакете `@mattacosta/php-parser` свой package.json (с этой зависимостью `@mattacosta/php-common`), а уже в зависимостях elephize в текущем файле убрать `@mattacosta/php-common` и добавить локальную зависимость:

```json
"@mattacosta/php-parser": "file:./src/vendor/php-parser"
```

Подробнее: https://stackoverflow.com/a/40116358

2020-08-19 12:52 UTC, ctizen commented on src/ts2php/components/cjsModules/phpParser.ts
> +        return $this->_impl->${name}(${args});
Вообще вопрос хороший, особенно в свете того что много кода где используются статические методы. В принципе можно предусмотреть и то, и другое, главное уложиться в интерфейс CommonjsModule, поставлю пунктик

2020-08-19 12:57 UTC, ctizen commented on .gitattributes
> +src/vendor/**/* linguist-generated
Справедливо, сделаем.
Отвечая на вопрос по месту - некоторые важные части библиотеки парсера в виде пакета тупо не работают. Точнее работают, но не срастаются по типам в рантайме при наследовании классов - ощущение что ее .d.ts почему-то отличаются от их представлений в .js, либо, как вариант, не предзначены для использования с текущими настройками typescript в elephize - подгонять настройки под каждую библиотеку считаю довольно странным. Всасывание исходников в виде ts-файлов помогло. Попробую впоследствии оставить ишью в гитхабе парсера, когда чуть разгребусь, т.к. это всё выглядит как баг.

2020-08-19 15:04 UTC, ctizen commented on src/ts2php/types.ts
> +  importRules: {
Добавлю в документацию

2020-08-19 15:05 UTC, ctizen commented on elephizerc.example.json
>    "customGlobals": {
Точно, и в документации тоже надо выпилить

2020-08-19 16:09 UTC, ctizen commented on src/ts2php/components/cjsModules/phpParser.ts
> +        return $this->_impl->${name}(${args});
Внезапно понял что доступ к свойствам реализован некорректно. Думаю что выпилю их.

2020-08-19 17:01 UTC, ctizen commented on package.json
> +    "@mattacosta/php-common": "^1.0.0-beta.4",
Чот в итоге подумал, потупил и завендорил php-common тоже. Разработчик не предполагает его использования вне php-parser.

2020-08-20 06:14 UTC, fix-fix commented on .gitattributes
> +src/vendor/**/* linguist-generated
Понятно, примерно так и думал про php-parser, учитывая что там 0 звёзд на гитхабе 😃

2020-08-20 06:16 UTC, fix-fix approved these changes

2020-08-20 11:06 UTC, merged